import type { Scholarship } from "./types";

export const scholarships: Scholarship[] = [
  {
    id: "global-excellence-oxford",
    name: "Global Excellence Scholarship",
    university: "University of Oxford",
    country: "United Kingdom",
    degreeLevel: "Master's",
    eligibleNationalities: ["All international students"],
    fieldsOfStudy: ["Computer Science", "Business", "Engineering"],
    minimumGpa: 3.5,
    englishRequirement: "IELTS 7.0 or TOEFL 100",
    fundingType: "Fully funded",
    fundingAmount: "Full tuition + £18,000 stipend",
    deadline: "2027-01-08",
    requiredDocuments: ["Academic transcripts", "CV", "2 references", "Personal statement"],
    applicationUrl: "https://www.ox.ac.uk/admissions/graduate/fees-and-funding",
    featured: true,
  },
  {
    id: "melbourne-international",
    name: "Melbourne Graduate Research Scholarship",
    university: "University of Melbourne",
    country: "Australia",
    degreeLevel: "PhD",
    eligibleNationalities: ["All international students"],
    fieldsOfStudy: ["All fields"],
    minimumGpa: 3.3,
    englishRequirement: "IELTS 6.5 or equivalent",
    fundingType: "Fully funded",
    fundingAmount: "Full tuition + A$38,500 yearly allowance",
    deadline: "2026-10-31",
    requiredDocuments: ["Research proposal", "Transcripts", "CV", "English test"],
    applicationUrl: "https://scholarships.unimelb.edu.au/awards/graduate-research-scholarships",
    featured: true,
  },
  {
    id: "daad-development",
    name: "DAAD Development-Related Postgraduate Scholarship",
    university: "Participating German Universities",
    country: "Germany",
    degreeLevel: "Master's",
    eligibleNationalities: ["Developing countries"],
    fieldsOfStudy: ["Development Studies", "Engineering", "Public Policy"],
    minimumGpa: 3.0,
    englishRequirement: "IELTS 6.0 or programme equivalent",
    fundingType: "Fully funded",
    fundingAmount: "Tuition + €992 monthly stipend",
    deadline: "2026-11-15",
    requiredDocuments: ["DAAD form", "Motivation letter", "CV", "Transcripts"],
    applicationUrl: "https://www.daad.de/en/studying-in-germany/scholarships/",
  },
  {
    id: "toronto-international",
    name: "International Scholar Award",
    university: "University of Toronto",
    country: "Canada",
    degreeLevel: "Bachelor's",
    eligibleNationalities: ["All international students"],
    fieldsOfStudy: ["All fields"],
    minimumGpa: 3.7,
    englishRequirement: "IELTS 6.5 or TOEFL 100",
    fundingType: "Partial funding",
    fundingAmount: "Up to C$45,000 over four years",
    deadline: "2026-11-07",
    requiredDocuments: ["School transcripts", "English test", "Activities list"],
    applicationUrl: "https://future.utoronto.ca/finances/awards/international-students/",
  },
  {
    id: "mext-research",
    name: "MEXT Research Scholarship",
    university: "Japanese National Universities",
    country: "Japan",
    degreeLevel: "Master's",
    eligibleNationalities: ["Countries with Japanese diplomatic relations"],
    fieldsOfStudy: ["All fields"],
    minimumGpa: 2.3,
    englishRequirement: "English or Japanese proficiency",
    fundingType: "Fully funded",
    fundingAmount: "Tuition + ¥144,000 monthly stipend + airfare",
    deadline: "2027-05-15",
    requiredDocuments: ["Research plan", "Degree certificate", "Medical form", "Recommendation"],
    applicationUrl: "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",
  },
  {
    id: "khalifa-graduate",
    name: "Graduate Scholarship",
    university: "Khalifa University",
    country: "United Arab Emirates",
    degreeLevel: "Master's",
    eligibleNationalities: ["All international students"],
    fieldsOfStudy: ["Engineering", "Computer Science", "Health Sciences"],
    minimumGpa: 3.0,
    englishRequirement: "IELTS 6.5 or TOEFL 91",
    fundingType: "Full tuition",
    fundingAmount: "Full tuition and support package",
    deadline: "2026-10-01",
    requiredDocuments: ["Transcripts", "CV", "Statement of purpose", "English test"],
    applicationUrl: "https://www.ku.ac.ae/graduate-scholarships",
  },
];

export const countries = ["Australia", "Canada", "Germany", "Japan", "United Arab Emirates", "United Kingdom", "United States"];
